<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>gameEditor</AssemblyName>
    <RootNamespace>GameEditor</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\resources\image\base_tiles.bmp">
      <Link>resources\image\base_tiles.bmp</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\resources\image\advanced_tiles.bmp">
      <Link>resources\image\advanced_tiles.bmp</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
